### ISSUE TITLE
java.lang.NullPointerException When starting ContactZendeskActivity

### ISSUE THREAD

**Issue by marcferna** [zendesk/sdk_demo_app_android#38]
First, i want to apologize if this is not the right place to put this but I could not find the Android SDK repo.

I just updated the Android SDK in our app from to `1.7.0.1` from `1.6.1.1` and i'm seeing the following crash when we start the `ContactZendeskActivity`.

**Activity code:**
```
ContactZendeskActivity.startActivity(activity, configuration);
```
Where `activity` is our main activity and configuration is a custom `ZendeskConfiguration`

**Crash stacktrace:**
```
08-16 13:46:13.225 6400-6400/com.***.*** E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.***.***, PID: 6400
java.lang.NullPointerException
    at com.zendesk.sdk.feedback.ui.ContactZendeskFragment.disableSendButton(ContactZendeskFragment.java:433)
    at com.zendesk.sdk.feedback.ui.ContactZendeskFragment.checkSendButtonState(ContactZendeskFragment.java:321)
    at com.zendesk.sdk.feedback.ui.ContactZendeskFragment.onPrepareOptionsMenu(ContactZendeskFragment.java:260)
    at android.support.v4.app.Fragment.performPrepareOptionsMenu(Fragment.java:2187)
    at android.support.v4.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManager.java:2270)
    at android.support.v4.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:340)
    at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:537)
    at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:297)
    at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
    at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
    at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
    at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5001)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)
```

I've also tried using your example from the [documentation](https://developer.zendesk.com/embeddables/docs/android/advancedtopics#sending-additional-data-in-the-ticket) with the same result

**Comment by baz8080** [comment]
Hi Marc,

We overhauled the thinking system in 1.7. have a look at this: https://developer.zendesk.com/embeddables/docs/android/migration#simplified-theming

Thanks,
Barry

**Comment by marcferna** [comment]
Hi Barry!

Thanks for your quick response, I should've read the migration notes more carefully... :sweat_smile:

Adding the following to my theme fixed it:
```
<item name="contactAttachmentIcon">@drawable/contact_attachment_icon_dark</item>
<item name="contactSendIcon">@drawable/contact_send_icon_selector_dark</item>
```

**Comment by baz8080** [comment]
Hi Marc,

Glad it is solved, sorry for the inconvenience! We had to use attributes so that we could better support dark and light themes.
